method: Pano3D
resume: False
finetune: True
weight: [
  # 'out/layout_estimation/23063018452589_rlsd/model_best.pth',
  # 'out/layout_estimation/21022217101943/model_best.pth',
  'out/layout_estimation/21022217101943_ft/model_best.pth'
  # 'out/layout_estimation/23061802031212_ig/model_best.pth',
]
seed: 123
device:
  use_gpu: True
  gpu_ids: '0'
  num_workers: 1
data:
  name: s3d
  split: /project/3dlg-hcvc/rlsd/data/psu/s3d
  expand_dis: 0.1
  g_feature_length: 64
model:
  detector:
    module: Detector2D
    config: 'COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml'
    # weight: 'out/detector/detector_mask_rcnn/model_final.pth'
    weight: 'out/detector/detector_mask_rcnn_rlsd/model_0029999.pth'
    score_thresh: 0.5
    min_iou: 0.25
    real: False
    pano: False
    cf_thresh: 0.3
    nms_thresh: 0.2
    nms_all_thresh: 0.4
  layout_estimation:
    module: HorizonNet
    loss: HorizonLoss
    backbone: resnet50
    use_rnn: True
optimizer:
  type: Adam
  lr: 1e-4
  betas: [0.9, 0.999]
  eps: 1e-08
  weight_decay: 0.0
scheduler:
  type: ReduceLROnPlateau
  patience: 10
  factor: 0.5
  threshold: 0.01
train:
  epochs: 50
  freeze: []
  batch_size: 2
val:
  batch_size: 2
test:
  batch_size: 2
log:
  vis_step: 0
  print_step: 20
  path: out/first_stage
  save_as_dataset: '/project/3dlg-hcvc/rlsd/data/psu/s3d_stage1_pano3d_ft'



